//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:

//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//find the sum of the even-valued terms.

exports.sumOfEvenFibonacciNumbers = function(n){
  
  var sum = 0; // this will be the result
  var x = 1; // set a value for x 
  var y = 1; // set a value for y
  var fib = 0;  // this will hold the sum of x and y

   for (var i = 0; fib < n; i++){
    fib = x + y;  // loop through and make Fib = to x + y
    x = y;  
    y = fib;
      if(fib % 2 === 0){  // only store the even numbers
        sum += fib;  // add up the even numbers
      }
    }
    return sum;
};
